#############################################################################
# Makefile for building: MacheDebuggeeParser
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  MacheDebuggeeParser.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile MacheDebuggeeParser.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/python2.7 -I/usr/include/c++/4.8.4 -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lpython2.7 -L./ -ljson -lQt5Widgets -L/usr/lib/x86_64-linux-gnu -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		machinedebugparam.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		machinedebugparam.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MacheDebuggeeParser.pro \
		MacheDebuggeeParser.pro
QMAKE_TARGET  = MacheDebuggeeParser
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MacheDebuggeeParser


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MacheDebuggeeParser.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MacheDebuggeeParser.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile MacheDebuggeeParser.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
MacheDebuggeeParser.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MacheDebuggeeParser.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/MacheDebuggeeParser1.0.0 || mkdir -p .tmp/MacheDebuggeeParser1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MacheDebuggeeParser1.0.0/ && $(COPY_FILE) --parents mainwindow.h machinedebugparam.h .tmp/MacheDebuggeeParser1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp machinedebugparam.cpp .tmp/MacheDebuggeeParser1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/MacheDebuggeeParser1.0.0/ && (cd `dirname .tmp/MacheDebuggeeParser1.0.0` && $(TAR) MacheDebuggeeParser1.0.0.tar MacheDebuggeeParser1.0.0 && $(COMPRESS) MacheDebuggeeParser1.0.0.tar) && $(MOVE) `dirname .tmp/MacheDebuggeeParser1.0.0`/MacheDebuggeeParser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MacheDebuggeeParser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/c++/4.8/atomic \
		/usr/include/c++/4.8/bits/atomic_base.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/c++/4.8/iterator \
		/usr/include/c++/4.8/bits/stream_iterator.h \
		/usr/include/c++/4.8/list \
		/usr/include/c++/4.8/bits/stl_list.h \
		/usr/include/c++/4.8/bits/list.tcc \
		/usr/include/c++/4.8/debug/list \
		/usr/include/c++/4.8/profile/list \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/c++/4.8/map \
		/usr/include/c++/4.8/bits/stl_tree.h \
		/usr/include/c++/4.8/bits/stl_map.h \
		/usr/include/c++/4.8/bits/stl_multimap.h \
		/usr/include/c++/4.8/debug/map \
		/usr/include/c++/4.8/debug/map.h \
		/usr/include/c++/4.8/debug/multimap.h \
		/usr/include/c++/4.8/profile/map \
		/usr/include/c++/4.8/profile/map.h \
		/usr/include/c++/4.8/profile/multimap.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/c++/4.8/atomic \
		/usr/include/c++/4.8/bits/atomic_base.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/c++/4.8/iterator \
		/usr/include/c++/4.8/bits/stream_iterator.h \
		/usr/include/c++/4.8/list \
		/usr/include/c++/4.8/bits/stl_list.h \
		/usr/include/c++/4.8/bits/list.tcc \
		/usr/include/c++/4.8/debug/list \
		/usr/include/c++/4.8/profile/list \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/c++/4.8/map \
		/usr/include/c++/4.8/bits/stl_tree.h \
		/usr/include/c++/4.8/bits/stl_map.h \
		/usr/include/c++/4.8/bits/stl_multimap.h \
		/usr/include/c++/4.8/debug/map \
		/usr/include/c++/4.8/debug/map.h \
		/usr/include/c++/4.8/debug/multimap.h \
		/usr/include/c++/4.8/profile/map \
		/usr/include/c++/4.8/profile/map.h \
		/usr/include/c++/4.8/profile/multimap.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/algorithm \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/bits/stl_algo.h \
		/usr/include/c++/4.8/bits/algorithmfwd.h \
		/usr/include/c++/4.8/bits/stl_heap.h \
		/usr/include/c++/4.8/bits/stl_tempbuf.h \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/random \
		/usr/include/c++/4.8/cmath \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/bits/random.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/bits/random.tcc \
		/usr/include/c++/4.8/numeric \
		/usr/include/c++/4.8/bits/stl_numeric.h \
		/usr/include/c++/4.8/parallel/numeric \
		/usr/include/c++/4.8/parallel/numericfwd.h \
		/usr/include/c++/4.8/parallel/iterator.h \
		/usr/include/c++/4.8/parallel/for_each.h \
		/usr/include/c++/4.8/parallel/par_loop.h \
		/usr/include/c++/4.8/parallel/omp_loop.h \
		/usr/include/c++/4.8/parallel/workstealing.h \
		/usr/include/c++/4.8/parallel/random_number.h \
		/usr/include/c++/4.8/tr1/random \
		/usr/include/c++/4.8/tr1/cmath \
		/usr/include/c++/4.8/tr1/gamma.tcc \
		/usr/include/c++/4.8/tr1/special_function_util.h \
		/usr/include/c++/4.8/tr1/bessel_function.tcc \
		/usr/include/c++/4.8/tr1/beta_function.tcc \
		/usr/include/c++/4.8/tr1/ell_integral.tcc \
		/usr/include/c++/4.8/tr1/exp_integral.tcc \
		/usr/include/c++/4.8/tr1/hypergeometric.tcc \
		/usr/include/c++/4.8/tr1/legendre_function.tcc \
		/usr/include/c++/4.8/tr1/modified_bessel_func.tcc \
		/usr/include/c++/4.8/tr1/poly_hermite.tcc \
		/usr/include/c++/4.8/tr1/poly_laguerre.tcc \
		/usr/include/c++/4.8/tr1/riemann_zeta.tcc \
		/usr/include/c++/4.8/tr1/random.h \
		/usr/include/c++/4.8/tr1/random.tcc \
		/usr/include/c++/4.8/parallel/for_each_selectors.h \
		/usr/include/c++/4.8/parallel/partial_sum.h \
		/usr/include/c++/4.8/parallel/algorithm \
		/usr/include/c++/4.8/parallel/algo.h \
		/usr/include/c++/4.8/parallel/sort.h \
		/usr/include/c++/4.8/parallel/checkers.h \
		/usr/include/c++/4.8/parallel/multiway_mergesort.h \
		/usr/include/c++/4.8/parallel/multiway_merge.h \
		/usr/include/c++/4.8/parallel/losertree.h \
		/usr/include/c++/4.8/parallel/multiseq_selection.h \
		/usr/include/c++/4.8/queue \
		/usr/include/c++/4.8/deque \
		/usr/include/c++/4.8/bits/stl_deque.h \
		/usr/include/c++/4.8/bits/deque.tcc \
		/usr/include/c++/4.8/debug/deque \
		/usr/include/c++/4.8/profile/deque \
		/usr/include/c++/4.8/bits/stl_queue.h \
		/usr/include/c++/4.8/parallel/quicksort.h \
		/usr/include/c++/4.8/parallel/partition.h \
		/usr/include/c++/4.8/parallel/balanced_quicksort.h \
		/usr/include/c++/4.8/parallel/queue.h \
		/usr/include/c++/4.8/parallel/omp_loop_static.h \
		/usr/include/c++/4.8/parallel/search.h \
		/usr/include/c++/4.8/parallel/random_shuffle.h \
		/usr/include/c++/4.8/parallel/merge.h \
		/usr/include/c++/4.8/parallel/unique_copy.h \
		/usr/include/c++/4.8/parallel/set_operations.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/c++/4.8/atomic \
		/usr/include/c++/4.8/bits/atomic_base.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/c++/4.8/iterator \
		/usr/include/c++/4.8/bits/stream_iterator.h \
		/usr/include/c++/4.8/list \
		/usr/include/c++/4.8/bits/stl_list.h \
		/usr/include/c++/4.8/bits/list.tcc \
		/usr/include/c++/4.8/debug/list \
		/usr/include/c++/4.8/profile/list \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/c++/4.8/map \
		/usr/include/c++/4.8/bits/stl_tree.h \
		/usr/include/c++/4.8/bits/stl_map.h \
		/usr/include/c++/4.8/bits/stl_multimap.h \
		/usr/include/c++/4.8/debug/map \
		/usr/include/c++/4.8/debug/map.h \
		/usr/include/c++/4.8/debug/multimap.h \
		/usr/include/c++/4.8/profile/map \
		/usr/include/c++/4.8/profile/map.h \
		/usr/include/c++/4.8/profile/multimap.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		ui_mainwindow.h \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QButtonGroup \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/QHeaderView \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtWidgets/QMenuBar \
		/usr/include/qt5/QtWidgets/qmenubar.h \
		/usr/include/qt5/QtWidgets/qmenu.h \
		/usr/include/qt5/QtWidgets/QStatusBar \
		/usr/include/qt5/QtWidgets/qstatusbar.h \
		/usr/include/qt5/QtWidgets/QToolBar \
		/usr/include/qt5/QtWidgets/qtoolbar.h \
		/usr/include/qt5/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

machinedebugparam.o: machinedebugparam.cpp machinedebugparam.h \
		/usr/include/c++/4.8/string \
		/usr/include/c++/4.8/bits/stringfwd.h \
		/usr/include/c++/4.8/bits/memoryfwd.h \
		/usr/include/c++/4.8/bits/char_traits.h \
		/usr/include/c++/4.8/bits/stl_algobase.h \
		/usr/include/c++/4.8/bits/functexcept.h \
		/usr/include/c++/4.8/bits/exception_defines.h \
		/usr/include/c++/4.8/bits/cpp_type_traits.h \
		/usr/include/c++/4.8/ext/type_traits.h \
		/usr/include/c++/4.8/ext/numeric_traits.h \
		/usr/include/c++/4.8/bits/stl_pair.h \
		/usr/include/c++/4.8/bits/move.h \
		/usr/include/c++/4.8/bits/concept_check.h \
		/usr/include/c++/4.8/bits/boost_concept_check.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_types.h \
		/usr/include/c++/4.8/type_traits \
		/usr/include/c++/4.8/bits/c++0x_warning.h \
		/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
		/usr/include/c++/4.8/debug/debug.h \
		/usr/include/c++/4.8/debug/macros.h \
		/usr/include/c++/4.8/debug/functions.h \
		/usr/include/c++/4.8/debug/formatter.h \
		/usr/include/c++/4.8/typeinfo \
		/usr/include/c++/4.8/exception \
		/usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
		/usr/include/c++/4.8/bits/exception_ptr.h \
		/usr/include/c++/4.8/bits/nested_exception.h \
		/usr/include/c++/4.8/bits/hash_bytes.h \
		/usr/include/c++/4.8/bits/stl_iterator.h \
		/usr/include/c++/4.8/parallel/algobase.h \
		/usr/include/c++/4.8/parallel/base.h \
		/usr/include/c++/4.8/bits/stl_function.h \
		/usr/include/c++/4.8/backward/binders.h \
		/usr/include/c++/4.8/parallel/features.h \
		/usr/include/c++/4.8/parallel/basic_iterator.h \
		/usr/include/c++/4.8/parallel/parallel.h \
		/usr/include/c++/4.8/parallel/compiletime_settings.h \
		/usr/include/c++/4.8/cstdio \
		/usr/include/c++/4.8/parallel/types.h \
		/usr/include/c++/4.8/cstdlib \
		/usr/include/c++/4.8/limits \
		/usr/include/c++/4.8/tr1/cstdint \
		/usr/include/c++/4.8/parallel/tags.h \
		/usr/include/c++/4.8/parallel/settings.h \
		/usr/include/c++/4.8/parallel/algorithmfwd.h \
		/usr/include/c++/4.8/parallel/find.h \
		/usr/include/c++/4.8/parallel/compatibility.h \
		/usr/include/c++/4.8/parallel/equally_split.h \
		/usr/include/c++/4.8/parallel/find_selectors.h \
		/usr/include/c++/4.8/bits/postypes.h \
		/usr/include/c++/4.8/cwchar \
		/usr/include/c++/4.8/cstdint \
		/usr/include/c++/4.8/bits/allocator.h \
		/usr/include/c++/4.8/bits/localefwd.h \
		/usr/include/c++/4.8/iosfwd \
		/usr/include/c++/4.8/cctype \
		/usr/include/c++/4.8/bits/ostream_insert.h \
		/usr/include/c++/4.8/bits/cxxabi_forced.h \
		/usr/include/c++/4.8/bits/range_access.h \
		/usr/include/c++/4.8/bits/basic_string.h \
		/usr/include/c++/4.8/ext/atomicity.h \
		/usr/include/c++/4.8/initializer_list \
		/usr/include/c++/4.8/ext/string_conversions.h \
		/usr/include/c++/4.8/cerrno \
		/usr/include/c++/4.8/bits/functional_hash.h \
		/usr/include/c++/4.8/bits/basic_string.tcc \
		/usr/include/c++/4.8/list \
		/usr/include/c++/4.8/bits/stl_list.h \
		/usr/include/c++/4.8/bits/list.tcc \
		/usr/include/c++/4.8/debug/list \
		/usr/include/c++/4.8/debug/safe_sequence.h \
		/usr/include/c++/4.8/debug/safe_base.h \
		/usr/include/c++/4.8/ext/concurrence.h \
		/usr/include/c++/4.8/debug/safe_sequence.tcc \
		/usr/include/c++/4.8/debug/safe_iterator.h \
		/usr/include/c++/4.8/debug/safe_iterator.tcc \
		/usr/include/c++/4.8/profile/list \
		/usr/include/c++/4.8/profile/base.h \
		/usr/include/c++/4.8/functional \
		/usr/include/c++/4.8/new \
		/usr/include/c++/4.8/tuple \
		/usr/include/c++/4.8/utility \
		/usr/include/c++/4.8/bits/stl_relops.h \
		/usr/include/c++/4.8/array \
		/usr/include/c++/4.8/stdexcept \
		/usr/include/c++/4.8/debug/array \
		/usr/include/c++/4.8/profile/array \
		/usr/include/c++/4.8/bits/uses_allocator.h \
		/usr/include/c++/4.8/profile/impl/profiler.h \
		/usr/include/c++/4.8/profile/impl/profiler_hash_func.h \
		/usr/include/c++/4.8/profile/impl/profiler_node.h \
		/usr/include/c++/4.8/vector \
		/usr/include/c++/4.8/bits/stl_construct.h \
		/usr/include/c++/4.8/ext/alloc_traits.h \
		/usr/include/c++/4.8/bits/alloc_traits.h \
		/usr/include/c++/4.8/bits/ptr_traits.h \
		/usr/include/c++/4.8/bits/stl_uninitialized.h \
		/usr/include/c++/4.8/bits/stl_vector.h \
		/usr/include/c++/4.8/bits/stl_bvector.h \
		/usr/include/c++/4.8/bits/vector.tcc \
		/usr/include/c++/4.8/debug/vector \
		/usr/include/c++/4.8/profile/vector \
		/usr/include/c++/4.8/profile/iterator_tracker.h \
		/usr/include/c++/4.8/profile/impl/profiler_trace.h \
		/usr/include/c++/4.8/unordered_map \
		/usr/include/c++/4.8/bits/hashtable.h \
		/usr/include/c++/4.8/bits/hashtable_policy.h \
		/usr/include/c++/4.8/bits/unordered_map.h \
		/usr/include/c++/4.8/debug/unordered_map \
		/usr/include/c++/4.8/debug/safe_unordered_container.h \
		/usr/include/c++/4.8/debug/safe_unordered_base.h \
		/usr/include/c++/4.8/debug/safe_unordered_container.tcc \
		/usr/include/c++/4.8/debug/safe_local_iterator.h \
		/usr/include/c++/4.8/debug/safe_local_iterator.tcc \
		/usr/include/c++/4.8/profile/unordered_map \
		/usr/include/c++/4.8/profile/unordered_base.h \
		/usr/include/c++/4.8/tr1/unordered_map \
		/usr/include/c++/4.8/tr1/type_traits \
		/usr/include/c++/4.8/tr1/functional_hash.h \
		/usr/include/c++/4.8/tr1/hashtable.h \
		/usr/include/c++/4.8/tr1/hashtable_policy.h \
		/usr/include/c++/4.8/tr1/unordered_map.h \
		/usr/include/c++/4.8/fstream \
		/usr/include/c++/4.8/istream \
		/usr/include/c++/4.8/ios \
		/usr/include/c++/4.8/bits/ios_base.h \
		/usr/include/c++/4.8/bits/locale_classes.h \
		/usr/include/c++/4.8/bits/locale_classes.tcc \
		/usr/include/c++/4.8/streambuf \
		/usr/include/c++/4.8/bits/streambuf.tcc \
		/usr/include/c++/4.8/bits/basic_ios.h \
		/usr/include/c++/4.8/bits/locale_facets.h \
		/usr/include/c++/4.8/cwctype \
		/usr/include/c++/4.8/bits/streambuf_iterator.h \
		/usr/include/c++/4.8/bits/locale_facets.tcc \
		/usr/include/c++/4.8/bits/basic_ios.tcc \
		/usr/include/c++/4.8/ostream \
		/usr/include/c++/4.8/bits/ostream.tcc \
		/usr/include/c++/4.8/bits/istream.tcc \
		/usr/include/c++/4.8/bits/codecvt.h \
		/usr/include/c++/4.8/bits/fstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_algos.h \
		/usr/include/c++/4.8/profile/impl/profiler_state.h \
		/usr/include/c++/4.8/profile/impl/profiler_hashtable_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_container_size.h \
		/usr/include/c++/4.8/sstream \
		/usr/include/c++/4.8/bits/sstream.tcc \
		/usr/include/c++/4.8/profile/impl/profiler_map_to_unordered_map.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_size.h \
		/usr/include/c++/4.8/profile/impl/profiler_vector_to_list.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_slist.h \
		/usr/include/c++/4.8/profile/impl/profiler_list_to_vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o machinedebugparam.o machinedebugparam.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

